# Site settings
title: "Jia Chenwei's Blog"
description: "A blog about AI and technology."
url: "https://jiachenwei.github.io"
baseurl: ""
future: true

# Build settings
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes settings
author:
  name: "Jia Chenwei"
  avatar: "https://avatars.githubusercontent.com/u/34532116"
  bio: "A blog about AI and technology."
  location: "IAIR, XJTU, China"
  email: "cwjia98@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jiachenwei"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO and Sitemap
sitemap:
  exclude:
    - "/assets/"

atom_feed:
  hide: true