# Site settings
title: "Jia Chenwei's Homepage"
description: "A blog about AI and technology."
url: "https://jiachenwei.github.io"
baseurl: ""
future: true

include:
  - _pages

# Build settings
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes settings
author:
  name: "Jia Chenwei"
  avatar: "https://avatars.githubusercontent.com/u/34532116"
  bio: "A blog about AI and technology."
  location: "IAIR, XJTU, China"
  email: "cwjia98@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jiachenwei"

# Pagination
paginate: 5
paginate_path: "/page:num/"

pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# SEO and Sitemap
sitemap:
  exclude:
    - "/assets/"

atom_feed:
  hide: true

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : "lunr"
lunr:
  search_within_pages    : true