theme: jekyll-theme-cayman
title: JiaChenwei's Blog
description: Bookmark this to keep an eye on my project updates!

favicon: "https://github.githubassets.com/favicons/favicon.svg"

show_downloads: false