# Site settings
title: "Jia Chenwei's Blog"
description: "A blog about AI and technology."
url: "https://jiachenwei.github.io"
baseurl: ""
future: true

# Build settings
# remote_theme: "mmistakes/minimal-mistakes"
plugins:
  # - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Minimal Mistakes settings
author:
  name: "Jia Chenwei"
  avatar: "https://avatars.githubusercontent.com/u/34532116"
  bio: "A blog about AI and technology."
  location: "China"
  email: "cwjia98@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jiachenwei"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO and Sitemap
sitemap:
  exclude:
    - "/assets/"

atom_feed:
  hide: true